[build.environment]
CI = "true"
NODE_VERSION = "10"
NPM_CONFIG_OPTIONAL = "false"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[build]
command = "node_modules/.bin/antora antora-playbook.yml --stacktrace --log-format=pretty"
# security policies
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-eval' 'unsafe-inline' data: filesystem: about: blob:;"
# redirect any netlify address url to real address
# redirect for home of sw and cloud docs
